### ISSUE TITLE
Non existing animations

### ISSUE THREAD

**Issue by SumnDaiy** [Scullyy/scully_emotemenu#12]
For example:
function EmoteMenu.ResetWalk()
    ResetPedMovementClipset(cache.ped)
    SetResourceKvp('animations_walkstyle', 'default')
    EmoteMenu.CurrentWalk = 'default'
end

In animations/walks.lua there is no such thing as 'default' its either 'move_m@multiplayer' for Male peds and 'move_f@multiplayer' for female peds.

**Comment by Scullyy** [comment]
Default works perfectly fine, it’s not an emote just an option to keep the peds default walk style. If it’s default it won’t change the walk style.

**Comment by SumnDaiy** [comment]
So if I want to use the export I cant since there is no animation named like that. So I have to set a new animation for a player before getting the walk anim.
(Trying to use the script exports for injured walking and when treated reset it to last player walk)
