### ISSUE TITLE
Server side objects

### ISSUE THREAD

**Issue by FjamZoo** [Scullyy/scully_emotemenu#22]
Move away from using client spawned entities that are synced, this will make it easier for people and eventually frameworks like qbox who uses this emote by default to swap to EntityLockdown to avoid cheaters spawning client sided objects.

**Comment by Scullyy** [comment]
Added in https://github.com/Scullyy/scully_emotemenu/commit/fa26c15edcfd8d8fa693507ecbdb7b9cd29b5b18
