### ISSUE TITLE
Bug: Props staying on map

### ISSUE THREAD

**Issue by Exyztence** [Scullyy/scully_emotemenu#29]
The props stay on the map after using them.
After using another emote the previous one is not being canceled so u can look like the tree as in the image below. Also, when scripts use emotes or players do props emotes then they stay on the map

![image](https://github.com/Scullyy/scully_emotemenu/assets/49649458/6357bd83-a934-4e33-8d02-9e7b1bf538df)
![image](https://github.com/Scullyy/scully_emotemenu/assets/49649458/70fa39c1-3830-4975-a2d1-1cbc47e7d87d)

**Comment by KuMoNDev** [comment]
i can confirm this is happening on my server too^

**Comment by niunisas** [comment]
Same, here.  With a lot of errors on server side. 
![image](https://github.com/Scullyy/scully_emotemenu/assets/55489629/ce737e0f-d2ef-4a70-b552-b58560d3db19)
