### ISSUE TITLE
Problem Adding Animations Rotations on Z ? (180 Degrees)

### ISSUE THREAD

**Issue by Marc85BPG** [Scullyy/scully_emotemenu#3]
I want to add Synchronized Anims - but always its wrong on Z Rotation 

i am looked for a variable like "zRot" or "ZRot Offset" or anything but there isnt.
so how can i rotate the ped / other part by 180 Degrees on Z ?

**Comment by Scullyy** [comment]
> I want to add Synchronized Anims - but always its wrong on Z Rotation
> 
> i am looked for a variable like "zRot" or "ZRot Offset" or anything but there isnt. so how can i rotate the ped / other part by 180 Degrees on Z ?

This already exists, it’s the 3rd parameter in the second position vector

**Comment by Marc85BPG** [comment]
Yah i am tooooo stupid bro :D 
after couple of hours i realized
vector3 (x,y,z)
vector3(rot-x,rot-y,rot-z) 
:D  lets close that.

Regards
