### ISSUE TITLE
Animations Wont work in Vehicles

### ISSUE THREAD

**Issue by JeyCraft** [Scullyy/scully_emotemenu#31]
Animations Wont work in Vehicles so Animal peds cant sit correct in cars ):

**Comment by Scullyy** [comment]
Update with more info and I will re-open the issue.

- Is the AllowedInVehicles config option enabled?
- Does this only happen with animal emotes?
- Provide screenshots + videos
- Provide reproduction steps so we can reproduce the issue and fix it
