### ISSUE TITLE
emote randomly reappears 

### ISSUE THREAD

**Issue by chelsey1992** [Scullyy/scully_emotemenu#32]
Hey. When I use an emote and hide it again with x or /e c, this emote randomly reappears out of nowhere during the evening. Is there a fix for this???

**Comment by Scullyy** [comment]
Do you have any emotes binded? You might have an emote binded and clicked it by accident.

**Comment by chelsey1992** [comment]
hey srry for the late response

no, I don't, several players suffer from this, not all of me

**Comment by Scullyy** [comment]
Can't seem to repro this, please send a video of it happening and make sure to always use the menu, /e c, or the cancel keybind to cancel the emote. Make sure nothing else is using your cancel keybind or they will conflict and it won't cancel correctly.
