### ISSUE TITLE
requestNamedPtfxAsset

### ISSUE THREAD

**Issue by Unavarage** [Scullyy/scully_emotemenu#5]
Hi, the issue of requestNamedPtfxAsset is still there but now it's in the line 1044, I don't know if it will get fixed, but I wanted to list it
![Névtelen](https://user-images.githubusercontent.com/31205336/207984681-01866e65-555a-429c-9777-44441c0a39e0.png)

**Comment by meltynetv2** [comment]
> Is their a specific animation this error will 100% show up with? I tested it with a few animations from the Champaign, Leaf Blower, Selfies, Vapes with no errors at all

I get the error for all animations with effects. The main one I test with is `pee`. The error even shows up when you press the effect button and don't even have an animation playing.

As well not sure if it matters, but I am using OneSync Legacy and not infinite. As well on the latest server artifact and game build.

If you guys need me to test anything I can. Although not sure what is causing it directly.

**Comment by Scullyy** [comment]
> Is their a specific animation this error will 100% show up with? I tested it with a few animations from the Champaign, Leaf Blower, Selfies, Vapes with no errors at all

Yeah very unusual, I don't get it either

**Comment by meltynetv2** [comment]
> > Is their a specific animation this error will 100% show up with? I tested it with a few animations from the Champaign, Leaf Blower, Selfies, Vapes with no errors at all
> 
> Yeah very unusual, I don't get it either

What server artifact are you using? As well are you using Legacy or Infinite for OneSync? Thanks, let me know!

**Comment by meltynetv2** [comment]
> > Is their a specific animation this error will 100% show up with? I tested it with a few animations from the Champaign, Leaf Blower, Selfies, Vapes with no errors at all
> 
> Yeah very unusual, I don't get it either

Hello good sir! I have found a fix for it on my end, it seems the statebag for the person doing the effect doesn't get set, but I believe it does for everyone else... I could be wrong. Anyways I added this above the TriggerServerEvent and it now shows the effect for me. `/e pee` works, but problem is with `/e camera` and the champaign spray emote effect it has problems with the flash being behind the person and the champaign coming from inside the person instead out the top of the bottle.

  ```
            LocalPlayer.state.ptfxAsset = data.Options.Ptfx.Asset
            LocalPlayer.state.ptfxName = data.Options.Ptfx.Name
            LocalPlayer.state.ptfxOffset = data.Options.Ptfx.Placement[1]
            LocalPlayer.state.ptfxRot = data.Options.Ptfx.Placement[2]
            LocalPlayer.state.ptfxScale = data.Options.Ptfx.Placement[3]
            LocalPlayer.state.ptfxColor = data.Options.Ptfx.Color
            LocalPlayer.state.ptfxPropNet = false

            TriggerServerEvent('scully_emotemenu:syncPtfx', data.Options.Ptfx.Asset, data.Options.Ptfx.Name, data.Options.Ptfx.Placement, data.Options.Ptfx.Color)
```

The above was set on the client. Not sure how to go about the rest without more time, so hopefully this can point you in the right direction of finding a fix for this? Thanks for the effort so far though!

**Comment by Scullyy** [comment]
> > > Is their a specific animation this error will 100% show up with? I tested it with a few animations from the Champaign, Leaf Blower, Selfies, Vapes with no errors at all
> > 
> > 
> > Yeah very unusual, I don't get it either
> 
> Hello good sir! I have found a fix for it on my end, it seems the statebag for the person doing the effect doesn't get set, but I believe it does for everyone else... I could be wrong. Anyways I added this above the TriggerServerEvent and it now shows the effect for me. `/e pee` works, but problem is with `/e camera` and the champaign spray emote effect it has problems with the flash being behind the person and the champaign coming from inside the person instead out the top of the bottle.
> 
> ```
>           LocalPlayer.state.ptfxAsset = data.Options.Ptfx.Asset
>           LocalPlayer.state.ptfxName = data.Options.Ptfx.Name
>           LocalPlayer.state.ptfxOffset = data.Options.Ptfx.Placement[1]
>           LocalPlayer.state.ptfxRot = data.Options.Ptfx.Placement[2]
>           LocalPlayer.state.ptfxScale = data.Options.Ptfx.Placement[3]
>           LocalPlayer.state.ptfxColor = data.Options.Ptfx.Color
>           LocalPlayer.state.ptfxPropNet = false
> 
>           TriggerServerEvent('scully_emotemenu:syncPtfx', data.Options.Ptfx.Asset, data.Options.Ptfx.Name, data.Options.Ptfx.Placement, data.Options.Ptfx.Color)
> ```
> 
> The above was set on the client. Not sure how to go about the rest without more time, so hopefully this can point you in the right direction of finding a fix for this? Thanks for the effort so far though!

I appreciate you looking into this but this just seems to be a workaround, I would like to find a proper solution as there seems to only be some people having the issue and not everyone. If we could just figure out what the differences are then I’m sure we can come up with a more permanent solution. Does everyone here having the issue have `set onesync on` in their server.cfg?

**Comment by Unavarage** [comment]
> > > > Is their a specific animation this error will 100% show up with? I tested it with a few animations from the Champaign, Leaf Blower, Selfies, Vapes with no errors at all
> > > 
> > > 
> > > Yeah very unusual, I don't get it either
> > 
> > Hello good sir! I have found a fix for it on my end, it seems the statebag for the person doing the effect doesn't get set, but I believe it does for everyone else... I could be wrong. Anyways I added this above the TriggerServerEvent and it now shows the effect for me. `/e pee` works, but problem is with `/e camera` and the champaign spray emote effect it has problems with the flash being behind the person and the champaign coming from inside the person instead out the top of the bottle.
> > 
> > ```
> >           LocalPlayer.state.ptfxAsset = data.Options.Ptfx.Asset
> >           LocalPlayer.state.ptfxName = data.Options.Ptfx.Name
> >           LocalPlayer.state.ptfxOffset = data.Options.Ptfx.Placement[1]
> >           LocalPlayer.state.ptfxRot = data.Options.Ptfx.Placement[2]
> >           LocalPlayer.state.ptfxScale = data.Options.Ptfx.Placement[3]
> >           LocalPlayer.state.ptfxColor = data.Options.Ptfx.Color
> >           LocalPlayer.state.ptfxPropNet = false
> > 
> >           TriggerServerEvent('scully_emotemenu:syncPtfx', data.Options.Ptfx.Asset, data.Options.Ptfx.Name, data.Options.Ptfx.Placement, data.Options.Ptfx.Color)
> > ```
> > 
> > The above was set on the client. Not sure how to go about the rest without more time, so hopefully this can point you in the right direction of finding a fix for this? Thanks for the effort so far though!
> 
> I appreciate you looking into this but this just seems to be a workaround, I would like to find a proper solution as there seems to only be some people having the issue and not everyone. If we could just figure out what the differences are then I’m sure we can come up with a more permanent solution. Does everyone here having the issue have `set onesync on` in their server.cfg? 

So actually i'm on the latest server artifact and onesync is on for me, it pops up only sometimes in the console when i'm on the server, but I haven't used any animation so these error comes by itself.

**Comment by meltynetv2** [comment]
> I appreciate you looking into this but this just seems to be a workaround, I would like to find a proper solution as there seems to only be some people having the issue and not everyone. If we could just figure out what the differences are then I’m sure we can come up with a more permanent solution. Does everyone here having the issue have `set onesync on` in their server.cfg?

Yes most definitely a workaround and not a permanent solution. I just wanted to show possibly there may be an issue with the statebags setting for the person emitting the effect. Yes I do have that in my config, although it says it is not using it.
```
## [txAdmin CFG validator]: onesync MUST only be set in the txAdmin settings page.
# set onesync legacy   # Infinity is not recommended for ESX
```

Furthermore I am on artifact 6136 and game build 2699.

**Comment by Scullyy** [comment]
> > I appreciate you looking into this but this just seems to be a workaround, I would like to find a proper solution as there seems to only be some people having the issue and not everyone. If we could just figure out what the differences are then I’m sure we can come up with a more permanent solution. Does everyone here having the issue have `set onesync on` in their server.cfg?
> 
> Yes most definitely a workaround and not a permanent solution. I just wanted to show possibly there may be an issue with the statebags setting for the person emitting the effect. Yes I do have that in my config, although it says it is not using it.
> 
> ```
> ## [txAdmin CFG validator]: onesync MUST only be set in the txAdmin settings page.
> # set onesync legacy   # Infinity is not recommended for ESX
> ```
> 
> Furthermore I am on artifact 6136 and game build 2699.

Yeah you need to have `set onesync on` in your server.cfg or have it enabled in TxAdmin. I think state bags only “sync” across players on onesync infinity

**Comment by Scullyy** [comment]
Can 2 people with the issue send a screenshot of their Config, we can see what similarities they have and I can compare it to my own

**Comment by meltynetv2** [comment]
> Yeah you need to have `set onesync on` in your server.cfg or have it enabled in TxAdmin. I think state bags only “sync” across players on onesync infinity

Yeah I believe it may need to be that way for players, but entity states I know for a fact sync with everyone on legacy. So is there maybe a way we can adjust the syncing for people with legacy OneSync to work? Maybe event based? Not sure if you can use the playerped entity for statebags instead seeming those sync? Just a random thought, not sure if it's possible. 

And for the config, did you want the config for scully_emote or the server.cfg? Thanks, let me know!

**Comment by Scullyy** [comment]
> Yeah I believe it may need to be that way for players, but entity states I know for a fact sync with everyone on legacy. So is there maybe a way we can adjust the syncing for people with legacy OneSync to work? Maybe event based? Not sure if you can use the playerped entity for statebags instead seeming those sync? Just a random thought, not sure if it's possible.
> 
> And for the config, did you want the config for scully_emote or the server.cfg? Thanks, let me know!

Just pushed a possible fix

**Comment by meltynetv2** [comment]
> > Yeah I believe it may need to be that way for players, but entity states I know for a fact sync with everyone on legacy. So is there maybe a way we can adjust the syncing for people with legacy OneSync to work? Maybe event based? Not sure if you can use the playerped entity for statebags instead seeming those sync? Just a random thought, not sure if it's possible.
> > And for the config, did you want the config for scully_emote or the server.cfg? Thanks, let me know!
> 
> Just pushed a possible fix

Wouldn't the fix only disable the ptfx keybind?

**Comment by Unavarage** [comment]
> > > Yeah I believe it may need to be that way for players, but entity states I know for a fact sync with everyone on legacy. So is there maybe a way we can adjust the syncing for people with legacy OneSync to work? Maybe event based? Not sure if you can use the playerped entity for statebags instead seeming those sync? Just a random thought, not sure if it's possible.
> > > And for the config, did you want the config for scully_emote or the server.cfg? Thanks, let me know!
> > 
> > Just pushed a possible fix
> 
> Wouldn't the fix only disable the ptfx keybind?

Yeah actually for now this is the only solution I could think of too, because when you disable the keybind It won't show the error anymore.

**Comment by meltynetv2** [comment]
I did try updating the state bags of the entity instead of the player and it seemed to sync across multiple clients YAY! So if maybe you can use the players ped as the entity and send the data that way you can update all clients on OneSync Legacy and Infinite. I don't have the time to do it right now, otherwise if no one does it when I get time I will definitely send you the code.

**Comment by Scullyy** [comment]
> > > Yeah I believe it may need to be that way for players, but entity states I know for a fact sync with everyone on legacy. So is there maybe a way we can adjust the syncing for people with legacy OneSync to work? Maybe event based? Not sure if you can use the playerped entity for statebags instead seeming those sync? Just a random thought, not sure if it's possible.
> > > And for the config, did you want the config for scully_emote or the server.cfg? Thanks, let me know!
> > 
> > 
> > Just pushed a possible fix
> 
> Wouldn't the fix only disable the ptfx keybind?

No, the keybind is meant to be disabled by default. The script enables it with you trigger an emote that has PTFX so it’ll still continue to work
