### ISSUE TITLE
Suggestion: Persistent Walkstyles

### ISSUE THREAD

**Issue by brunoodle** [Scullyy/scully_emotemenu#52]
Hi, I was wondering if it would be possible to incorporate persistent walk styles, so when you log out/server restarts your walk style will be saved.

Thanks for all your work!

**Comment by Scullyy** [comment]
This is already a feature.

**Comment by brunoodle** [comment]
It appears I am having an issue then. After relogging or restarting the server the walk style does not save for me. No errors from the script. Running on latest version of emotemenu and QB. Any ideas as to what it could be?
