### ISSUE TITLE
[Bug] Zombie Arms

### ISSUE THREAD

**Issue by Cocaina-Ricky** [Scullyy/scully_emotemenu#58]
Hey there,

I really enjoy using the emote menu but sometimes, I've realised that people get stuck in "zombie arms" emote and cannot stop it until they relog. 

Are you aware of this?

**Comment by Roekeloossss** [comment]
did u fixed this ? i have this problem also @Cocaina-Ricky

**Comment by Scullyy** [comment]
Can't repro
