### ISSUE TITLE
Cannot change menu keybind

### ISSUE THREAD

**Issue by TheKingsman11** [Scullyy/scully_emotemenu#64]
When i try to change the keybind, line 37. 

MenuKeybind = 'F5', -- List of keys here: https://docs.fivem.net/docs/game-references/input-mapper-parameter-ids/keyboard/
    -- You can change the menu position here.

I changed it to F4 and it is still stuck to F5.. any help?

**Comment by Scullyy** [comment]
This is for reporting issues such as bugs not installation support. Read the read me for support.
