### ISSUE TITLE
i dont know if this is a bugg

### ISSUE THREAD

**Issue by Roekeloossss** [Scullyy/scully_emotemenu#66]
okay but i dont know if its a bug but my random players get random this animation everytime and they cant fix it to normal so i want to delete this animation 
[![image|457x500](upload://epk0YY5AhZ7JBYmWsmFdpoG81bg.jpeg)](https://forum-cfx-re.akamaized.net/original/5X/6/4/f/b/64fb3c32789a5706fa2c15ec98123e5f623175de.jpeg)

**Comment by Scullyy** [comment]
cant repro

**Comment by Roekeloossss** [comment]
what u mean @Scullyy
