### ISSUE TITLE
Props from Scenario emotes dont clear

### ISSUE THREAD

**Issue by Mkeefeus** [Scullyy/scully_emotemenu#7]
The example I noticed is with the weld scenario. When you cancel the emote the welder stays attached to the peds hand. This also seems to happen with other scenarios, such as bbq (male)
![image](https://user-images.githubusercontent.com/27903055/210614519-0db3a0fb-ab03-4291-bbb7-458bd3e89f30.png)
![image](https://user-images.githubusercontent.com/27903055/210614724-dc56bc1f-a1f1-42f0-ace4-0b0cee33e291.png)

**Comment by Mkeefeus** [comment]
In the script I was working in I resolved the issue like this if it helps
`
exports.scully_emotemenu:CancelAnimation()
local prop =  GetClosestObjectOfType(GetEntityCoords(cache.ped), 1.0, `prop_weld_torch`, false, false, false)
if prop then
    SetEntityAsMissionEntity(prop, true, true)
    DeleteEntity(prop)
end
`

**Comment by Scullyy** [comment]
I can't seem to reproduce this, closing for now...script solution provided by OP above.
