### ISSUE TITLE
tablet2 is upside-down 

### ISSUE THREAD

**Issue by Darahz** [Scullyy/scully_emotemenu#70]
**Describe the bug**
Tablet2 prop emote is upside-down.

**To Reproduce**
e tablet2

**Expected behavior**
Just want the tablet to be the right way

**Screenshots**
![image](https://github.com/Scullyy/scully_emotemenu/assets/35222814/e5425443-ee60-4c0a-9d1d-65c32d2340cf)

**Additional context**
Easy fix. But people keep commenting on it and i have to rotate it around each time we update the script

```LUA
Placement = {
    vector3(-0.050000, 0.000000, 0.000000),
    vector3(0.000000, -90.000000, 0.000000),
},
```
TADA
![image](https://github.com/Scullyy/scully_emotemenu/assets/35222814/9d77aee3-3d43-40b5-87d4-d18c553cc25b)

**Comment by Scullyy** [comment]
If you have the solution please make a PR instead and mark this issue #70 as resolved.

**Comment by Darahz** [comment]
Pull request made
